import { AccountAbstractionProvider } from "@/Context/accountAbstractionContext";
import "./globals.css";
import { Inter, Jura } from "next/font/google";
import { NavBar } from "./components";
import { AboutUs } from "./views";
import { MintingProvider } from "@/Context/mintingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jura = Jura({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jura.className} Bg text-white`}>
        <AccountAbstractionProvider>
          <MintingProvider>
            <NavBar />
            <AboutUs />
            {children}
          </MintingProvider>
        </AccountAbstractionProvider>
      </body>
    </html>
  );
}
